language: go

sudo: false

go:
  - 1.6
  - tip

env:
  - CGO_ENABLED=0

addons:
  ssh_known_hosts:
  - hub.blitznote.com

install:
  - export TMPDIR=$HOME/tmp
  - mkdir -p $TMPDIR
  - go get -d -t blitznote.com/src/caddy.upload
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/gordonklaus/ineffassign

before_script:
  - cd ../../../blitznote.com/src/caddy.upload

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./.

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
